//! Menu bar host for Calendo.
//!
//! There is no main window. The process is an accessory: a status item whose
//! left click opens a month popover, and a settings window opened on demand.

mod glass;
mod beep;
mod settings;

use settings::{AppSettings, SettingsStore};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Mutex;
use std::time::Duration;
use tauri::menu::{Menu, MenuItem, PredefinedMenuItem};
use tauri::tray::{MouseButton, MouseButtonState, TrayIconBuilder, TrayIconEvent};
use tauri::{
    ActivationPolicy, AppHandle, Emitter, LogicalPosition, LogicalSize, Manager, PhysicalPosition,
    PhysicalSize, Position, Size, State, Theme, WebviewUrl, WebviewWindow, WebviewWindowBuilder,
    WindowEvent,
};
use tauri_plugin_autostart::{MacosLauncher, ManagerExt as AutostartManagerExt};

const CALENDAR_LABEL: &str = "calendar";
const SETTINGS_LABEL: &str = "settings";
const TRAY_ID: &str = "calendo";
const AUTOSTART_ARG: &str = "--autostart";
const CALENDAR_WIDTH: f64 = 288.0;
const CALENDAR_WIDTH_WEEKS: f64 = 312.0;
const CALENDAR_HEIGHT: f64 = 348.0;
const SETTINGS_WIDTH: f64 = 560.0;
const SETTINGS_HEIGHT: f64 = 560.0;

/// Dated filled glyphs, one image per day of the month. Generated by `pnpm icon`.
const TRAY_FILLED: [&[u8]; 31] = [
    include_bytes!("../../icons/tray/filled/day-01.png"),
    include_bytes!("../../icons/tray/filled/day-02.png"),
    include_bytes!("../../icons/tray/filled/day-03.png"),
    include_bytes!("../../icons/tray/filled/day-04.png"),
    include_bytes!("../../icons/tray/filled/day-05.png"),
    include_bytes!("../../icons/tray/filled/day-06.png"),
    include_bytes!("../../icons/tray/filled/day-07.png"),
    include_bytes!("../../icons/tray/filled/day-08.png"),
    include_bytes!("../../icons/tray/filled/day-09.png"),
    include_bytes!("../../icons/tray/filled/day-10.png"),
    include_bytes!("../../icons/tray/filled/day-11.png"),
    include_bytes!("../../icons/tray/filled/day-12.png"),
    include_bytes!("../../icons/tray/filled/day-13.png"),
    include_bytes!("../../icons/tray/filled/day-14.png"),
    include_bytes!("../../icons/tray/filled/day-15.png"),
    include_bytes!("../../icons/tray/filled/day-16.png"),
    include_bytes!("../../icons/tray/filled/day-17.png"),
    include_bytes!("../../icons/tray/filled/day-18.png"),
    include_bytes!("../../icons/tray/filled/day-19.png"),
    include_bytes!("../../icons/tray/filled/day-20.png"),
    include_bytes!("../../icons/tray/filled/day-21.png"),
    include_bytes!("../../icons/tray/filled/day-22.png"),
    include_bytes!("../../icons/tray/filled/day-23.png"),
    include_bytes!("../../icons/tray/filled/day-24.png"),
    include_bytes!("../../icons/tray/filled/day-25.png"),
    include_bytes!("../../icons/tray/filled/day-26.png"),
    include_bytes!("../../icons/tray/filled/day-27.png"),
    include_bytes!("../../icons/tray/filled/day-28.png"),
    include_bytes!("../../icons/tray/filled/day-29.png"),
    include_bytes!("../../icons/tray/filled/day-30.png"),
    include_bytes!("../../icons/tray/filled/day-31.png"),
];

const TRAY_CALENDAR: &[u8] = include_bytes!("../../icons/tray/calendar.png");

struct AppState {
    settings: Mutex<SettingsStore>,
    ignore_calendar_blur: AtomicBool,
    calendar_pinned: AtomicBool,
}

fn calendar_width(show_week_numbers: bool) -> f64 {
    if show_week_numbers {
        CALENDAR_WIDTH_WEEKS
    } else {
        CALENDAR_WIDTH
    }
}

fn user_data_dir(app: &AppHandle) -> PathBuf {
    if cfg!(target_os = "macos") {
        if let Some(home) = std::env::var_os("HOME") {
            return Path::new(&home).join("Library/Application Support/Calendo");
        }
    }
    app.path()
        .app_config_dir()
        .unwrap_or_else(|_| PathBuf::from("."))
}

fn merge_settings(current: &AppSettings, patch: &serde_json::Value) -> Result<AppSettings, String> {
    let mut merged =
        serde_json::to_value(current).map_err(|error| format!("Invalid settings: {error}"))?;
    if let (Some(base), Some(fields)) = (merged.as_object_mut(), patch.as_object()) {
        for (key, value) in fields {
            base.insert(key.clone(), value.clone());
        }
    }
    serde_json::from_value(merged).map_err(|error| format!("Invalid settings patch: {error}"))
}

fn set_launch_at_login(app: &AppHandle, enabled: bool) {
    let manager = app.autolaunch();
    let _ = if enabled {
        manager.enable()
    } else {
        manager.disable()
    };
}

fn show_week_numbers(app: &AppHandle) -> bool {
    app.state::<AppState>()
        .settings
        .lock()
        .map(|store| store.value().show_week_numbers)
        .unwrap_or(false)
}

fn close_calendar(app: &AppHandle) {
    if let Some(window) = app.get_webview_window(CALENDAR_LABEL) {
        let _ = window.hide();
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
struct ScreenBounds {
    x: f64,
    y: f64,
    width: f64,
    height: f64,
}

fn point_in_screen(x: f64, y: f64, screen: ScreenBounds) -> bool {
    x >= screen.x && y >= screen.y && x < screen.x + screen.width && y < screen.y + screen.height
}

#[cfg(test)]
fn screen_containing(screens: &[ScreenBounds], x: f64, y: f64) -> Option<ScreenBounds> {
    screens
        .iter()
        .copied()
        .find(|screen| point_in_screen(x, y, *screen))
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum PopoverPlacement {
    Below,
    Above,
}

fn calendar_window_size(show_week_numbers: bool) -> (f64, f64) {
    (
        calendar_width(show_week_numbers),
        CALENDAR_HEIGHT + glass::CARET_HEIGHT,
    )
}

fn window_theme(theme: &str) -> Option<Theme> {
    match theme {
        "light" => Some(Theme::Light),
        "dark" => Some(Theme::Dark),
        _ => None,
    }
}

fn apply_window_theme(window: &WebviewWindow, theme: &str) {
    glass::apply_appearance(window, theme);
    let _ = window.set_theme(window_theme(theme));
}

fn apply_app_theme(app: &AppHandle, theme: &str) {
    if let Some(window) = app.get_webview_window(CALENDAR_LABEL) {
        apply_window_theme(&window, theme);
    }
    if let Some(window) = app.get_webview_window(SETTINGS_LABEL) {
        let _ = window.set_theme(window_theme(theme));
    }
}

/// Distance from the window's left edge to the caret tip, so the triangle
/// still points at the menu bar icon after the window is clamped to the screen.
fn caret_offset(window_x: f64, window_w: f64, tray_x: f64, tray_w: f64) -> f64 {
    const INSET: f64 = 22.0;
    let center = tray_x + tray_w / 2.0 - window_x;
    if window_w <= INSET * 2.0 {
        return window_w / 2.0;
    }
    center.clamp(INSET, window_w - INSET)
}

fn sync_caret(window: &WebviewWindow, offset: f64, placement: PopoverPlacement) {
    let side = match placement {
        PopoverPlacement::Below => "below",
        PopoverPlacement::Above => "above",
    };
    let _ = window.eval(format!(
        "document.documentElement.style.setProperty('--caret-x','{offset:.1}px');\
         var shell=document.querySelector('.shell');\
         if(shell)shell.setAttribute('data-placement','{side}');"
    ));
}

/// Top-left of the popover, in the same coordinate space as the tray and screen.
fn popover_origin(
    tray_x: f64,
    tray_y: f64,
    tray_w: f64,
    tray_h: f64,
    win_w: f64,
    win_h: f64,
    screen: ScreenBounds,
) -> (f64, f64, PopoverPlacement) {
    const GAP: f64 = 2.0;
    const PAD: f64 = 8.0;
    let mut x = tray_x + tray_w / 2.0 - win_w / 2.0;
    let mut y = tray_y + tray_h + GAP;
    let mut placement = PopoverPlacement::Below;
    let min_x = screen.x + PAD;
    let max_x = screen.x + screen.width - win_w - PAD;
    if max_x >= min_x {
        x = x.clamp(min_x, max_x);
    }
    let max_y = screen.y + screen.height - win_h - PAD;
    if y > max_y {
        y = tray_y - win_h - GAP;
        placement = PopoverPlacement::Above;
    }
    (x, y, placement)
}

fn position_calendar(app: &AppHandle, tray_rect: tauri::Rect) {
    let Some(window) = app.get_webview_window(CALENDAR_LABEL) else {
        return;
    };
    let (width, height) = calendar_window_size(show_week_numbers(app));
    let fallback_scale = window.scale_factor().unwrap_or(1.0);
    // Tray events already carry physical pixels, converted with the status
    // item's own scale. The hidden window often still sits on the primary
    // display, whose scale and bounds are the wrong ones to use here —
    // especially with a Retina laptop and a 1× external.
    let tray_pos: PhysicalPosition<f64> = tray_rect.position.to_physical(fallback_scale);
    let tray_size: PhysicalSize<f64> = tray_rect.size.to_physical(fallback_scale);
    let tray_cx = tray_pos.x + tray_size.width / 2.0;
    let tray_cy = tray_pos.y + tray_size.height / 2.0;

    let monitors = window.available_monitors().ok().unwrap_or_default();
    let monitor = monitors
        .iter()
        .find(|monitor| {
            point_in_screen(
                tray_cx,
                tray_cy,
                ScreenBounds {
                    x: monitor.position().x as f64,
                    y: monitor.position().y as f64,
                    width: monitor.size().width as f64,
                    height: monitor.size().height as f64,
                },
            )
        })
        .cloned()
        .or_else(|| window.primary_monitor().ok().flatten());
    let scale = monitor
        .as_ref()
        .map(|monitor| monitor.scale_factor())
        .unwrap_or(fallback_scale);

    let tray_x = tray_pos.x / scale;
    let tray_y = tray_pos.y / scale;
    let tray_w = tray_size.width / scale;
    let tray_h = tray_size.height / scale;
    let screen = monitor
        .as_ref()
        .map(|monitor| ScreenBounds {
            x: monitor.position().x as f64 / scale,
            y: monitor.position().y as f64 / scale,
            width: monitor.size().width as f64 / scale,
            height: monitor.size().height as f64 / scale,
        })
        .unwrap_or(ScreenBounds {
            x: tray_x,
            y: tray_y,
            width: width.max(tray_w),
            height: height.max(tray_h),
        });
    let (x, y, placement) = popover_origin(tray_x, tray_y, tray_w, tray_h, width, height, screen);

    let _ = window.set_size(Size::Logical(LogicalSize::new(width, height)));
    // Logical points, not physical: set_position converts physical coords with
    // the *window's* current scale, which is still the other display's.
    let _ = window.set_position(Position::Logical(LogicalPosition::new(x, y)));
    sync_caret(&window, caret_offset(x, width, tray_x, tray_w), placement);
}

fn show_calendar(app: &AppHandle, tray_rect: tauri::Rect) {
    position_calendar(app, tray_rect);
    if let Some(window) = app.get_webview_window(CALENDAR_LABEL) {
        let _ = window.show();
        // Showing can let AppKit park the window on the previous screen.
        position_calendar(app, tray_rect);
        let _ = window.set_focus();
    }
    let _ = app.emit("calendar-shown", ());
}

fn toggle_calendar(app: &AppHandle, tray_rect: tauri::Rect) {
    let visible = app
        .get_webview_window(CALENDAR_LABEL)
        .and_then(|window| window.is_visible().ok())
        .unwrap_or(false);
    if visible {
        app.state::<AppState>()
            .ignore_calendar_blur
            .store(true, Ordering::SeqCst);
        close_calendar(app);
        return;
    }
    show_calendar(app, tray_rect);
}

fn present_settings(app: &AppHandle) {
    close_calendar(app);
    let _ = app.set_activation_policy(ActivationPolicy::Regular);
    if let Some(window) = app.get_webview_window(SETTINGS_LABEL) {
        let _ = window.unminimize();
        let _ = window.show();
        let _ = window.set_focus();
    }
}

fn dismiss_settings(app: &AppHandle) {
    if let Some(window) = app.get_webview_window(SETTINGS_LABEL) {
        let _ = window.hide();
    }
    let _ = app.set_activation_policy(ActivationPolicy::Accessory);
}

fn handle_menu_action(app: &AppHandle, id: &str) {
    match id {
        "settings" => present_settings(app),
        "quit" => app.exit(0),
        _ => {}
    }
}

fn build_tray_menu(app: &AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let settings = MenuItem::with_id(app, "settings", "Settings…", true, Some("CmdOrCtrl+,"))?;
    let quit = MenuItem::with_id(app, "quit", "Quit Calendo", true, Some("CmdOrCtrl+Q"))?;
    let separator = PredefinedMenuItem::separator(app)?;
    Menu::with_items(
        app,
        &[
            &settings as &dyn tauri::menu::IsMenuItem<tauri::Wry>,
            &separator,
            &quit,
        ],
    )
}

fn build_tray(app: &AppHandle) -> tauri::Result<()> {
    let menu = build_tray_menu(app)?;
    let icon = tauri::image::Image::from_bytes(include_bytes!("../../icons/tray-icon.png"))?;
    TrayIconBuilder::with_id(TRAY_ID)
        .icon(icon)
        .icon_as_template(true)
        .tooltip("Calendo")
        .menu(&menu)
        .show_menu_on_left_click(false)
        .on_menu_event(|app, event| handle_menu_action(app, event.id().as_ref()))
        .on_tray_icon_event(|tray, event| {
            if let TrayIconEvent::Click {
                button: MouseButton::Left,
                button_state: MouseButtonState::Up,
                rect,
                ..
            } = event
            {
                toggle_calendar(tray.app_handle(), rect);
            }
        })
        .build(app)?;
    Ok(())
}

fn build_calendar_window(app: &AppHandle) -> tauri::Result<()> {
    let window =
        WebviewWindowBuilder::new(app, CALENDAR_LABEL, WebviewUrl::App("calendar.html".into()))
            .title("Calendo")
            .inner_size(CALENDAR_WIDTH, CALENDAR_HEIGHT + glass::CARET_HEIGHT)
            .decorations(false)
            .transparent(true)
            .shadow(true)
            .resizable(false)
            .always_on_top(true)
            .visible_on_all_workspaces(true)
            .skip_taskbar(true)
            .accept_first_mouse(true)
            .visible(false)
            .focused(false)
            .build()?;

    glass::apply_calendar_glass(&window);

    let handle = app.clone();
    window.on_window_event(move |event| match event {
        WindowEvent::Focused(false) => {
            let app = handle.clone();
            std::thread::spawn(move || {
                std::thread::sleep(Duration::from_millis(180));
                if app
                    .state::<AppState>()
                    .calendar_pinned
                    .load(Ordering::SeqCst)
                {
                    return;
                }
                if app
                    .state::<AppState>()
                    .ignore_calendar_blur
                    .swap(false, Ordering::SeqCst)
                {
                    return;
                }
                if let Some(window) = app.get_webview_window(CALENDAR_LABEL) {
                    let focused = window.is_focused().unwrap_or(false);
                    let visible = window.is_visible().unwrap_or(false);
                    if visible && !focused {
                        let _ = window.hide();
                    }
                }
            });
        }
        WindowEvent::CloseRequested { api, .. } => {
            api.prevent_close();
            close_calendar(&handle);
        }
        _ => {}
    });
    Ok(())
}

fn build_settings_window(app: &AppHandle) -> tauri::Result<()> {
    let window =
        WebviewWindowBuilder::new(app, SETTINGS_LABEL, WebviewUrl::App("settings.html".into()))
            .title("Calendo Settings")
            .inner_size(SETTINGS_WIDTH, SETTINGS_HEIGHT)
            .resizable(false)
            .skip_taskbar(false)
            .visible(false)
            .center()
            .build()?;

    let handle = app.clone();
    window.on_window_event(move |event| {
        if let WindowEvent::CloseRequested { api, .. } = event {
            api.prevent_close();
            dismiss_settings(&handle);
        }
    });
    Ok(())
}

fn spawn_clock(app: AppHandle) {
    std::thread::spawn(move || loop {
        std::thread::sleep(Duration::from_secs(30));
        let _ = app.emit("clock-tick", ());
    });
}

#[tauri::command]
fn get_settings(state: State<AppState>) -> Result<AppSettings, String> {
    state
        .settings
        .lock()
        .map(|store| store.value())
        .map_err(|error| error.to_string())
}

#[tauri::command]
fn update_settings(
    app: AppHandle,
    state: State<AppState>,
    patch: serde_json::Value,
) -> Result<AppSettings, String> {
    let mut store = state.settings.lock().map_err(|error| error.to_string())?;
    let previous = store.value();
    let next = merge_settings(&previous, &patch)?;
    let saved = store.update(next);
    drop(store);
    if saved.launch_at_login != previous.launch_at_login {
        set_launch_at_login(&app, saved.launch_at_login);
    }
    if saved.show_week_numbers != previous.show_week_numbers {
        if let Some(window) = app.get_webview_window(CALENDAR_LABEL) {
            if window.is_visible().unwrap_or(false) {
                let (width, height) = calendar_window_size(saved.show_week_numbers);
                let _ = window.set_size(Size::Logical(LogicalSize::new(width, height)));
            }
        }
    }
    if saved.theme != previous.theme {
        apply_app_theme(&app, &saved.theme);
    }
    let _ = app.emit("settings-changed", &saved);
    Ok(saved)
}

/// Paints exactly one menu bar style: plain text or a glyph.
///
/// `title` is None for icon-only. `icon_day` is None when the style has no
/// date. `image` carries the framed glyph, which the renderer draws because it
/// holds text that the baked PNGs cannot.
#[tauri::command]
fn set_tray_label(
    app: AppHandle,
    title: Option<String>,
    icon_day: Option<u8>,
    style: String,
    image: Option<Vec<u8>>,
) {
    let _ = app.clone().run_on_main_thread(move || {
        let Some(tray) = app.tray_by_id(TRAY_ID) else {
            return;
        };
        // On macOS, set_title(None) leaves the previous native title intact.
        // Explicitly clear it for every glyph style when leaving plain text.
        let text = if style == "none" {
            title.as_deref().unwrap_or("")
        } else {
            ""
        };
        let _ = tray.set_title(Some(text));
        let bytes: Option<&[u8]> = match style.as_str() {
            "none" => None,
            "framed" => image.as_deref(),
            "calendar" => Some(TRAY_CALENDAR),
            _ => icon_day
                .filter(|day| (1..=31).contains(day))
                .and_then(|day| TRAY_FILLED.get(usize::from(day) - 1).copied()),
        };
        let glyph = bytes.and_then(|data| tauri::image::Image::from_bytes(data).ok());
        let showing = glyph.is_some();
        let _ = tray.set_icon(glyph);
        if showing {
            let _ = tray.set_icon_as_template(true);
        }
    });
}

/// Plays the bundled hourly chime for both the clock and Settings preview.
#[tauri::command]
fn beep(app: AppHandle) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        let path = app.path()
            .resolve("resources/beep.mp3", tauri::path::BaseDirectory::Resource)
            .map_err(|error| error.to_string())?;
        beep::play_native(&path, beep::beep_playback_volume())?;
    }
    Ok(())
}

#[tauri::command]
fn hide_calendar(app: AppHandle) {
    close_calendar(&app);
}

#[tauri::command]
fn set_calendar_pinned(state: State<AppState>, pinned: bool) {
    state.calendar_pinned.store(pinned, Ordering::SeqCst);
}

#[tauri::command]
fn open_settings(app: AppHandle) {
    present_settings(&app);
}

#[tauri::command]
fn quit_app(app: AppHandle) {
    app.exit(0);
}

#[tauri::command]
fn app_version(app: AppHandle) -> String {
    app.package_info().version.to_string()
}

#[tauri::command]
fn check_for_updates() -> Result<String, String> {
    let output = std::process::Command::new("/usr/bin/curl")
        .args([
            "-fsSL",
            "--retry", "2",
            "--connect-timeout", "10",
            "https://api.github.com/repos/vipiny35/calendo/releases/latest",
            "-H", "Accept: application/vnd.github+json",
            "-H", "User-Agent: Calendo",
        ])
        .output()
        .map_err(|error| error.to_string())?;
    if !output.status.success() {
        let detail = String::from_utf8_lossy(&output.stderr).trim().to_owned();
        return Err(if detail.is_empty() {
            format!("Update server request failed ({})", output.status)
        } else {
            detail
        });
    }
    let json: serde_json::Value = serde_json::from_slice(&output.stdout)
        .map_err(|error| error.to_string())?;
    json.get("tag_name")
        .and_then(serde_json::Value::as_str)
        .map(str::to_owned)
        .ok_or_else(|| "No release found".into())
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_autostart::init(
            MacosLauncher::LaunchAgent,
            Some(vec![AUTOSTART_ARG]),
        ))
        .setup(|app| {
            let _ = app.set_activation_policy(ActivationPolicy::Accessory);
            let user_data = user_data_dir(app.handle());
            std::fs::create_dir_all(&user_data).ok();
            let store = SettingsStore::load(user_data);
            let initial = store.value();
            app.manage(AppState {
                settings: Mutex::new(store),
                ignore_calendar_blur: AtomicBool::new(false),
                calendar_pinned: AtomicBool::new(false),
            });
            set_launch_at_login(app.handle(), initial.launch_at_login);
            build_calendar_window(app.handle())?;
            build_settings_window(app.handle())?;
            apply_app_theme(app.handle(), &initial.theme);
            build_tray(app.handle())?;
            spawn_clock(app.handle().clone());
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            get_settings,
            update_settings,
            set_tray_label,
            beep,
            hide_calendar,
            set_calendar_pinned,
            open_settings,
            quit_app,
            app_version,
            check_for_updates,
        ])
        .run(tauri::generate_context!())
        .expect("Calendo failed to start");
}

#[cfg(test)]
mod tests {
    use super::*;

    // Retina laptop below a 1× external, matching a typical arrangement:
    // laptop (0, 0) 1512×982 @2x, external (−197, −1080) 1920×1080 @1x.
    const LAPTOP: ScreenBounds = ScreenBounds {
        x: 0.0,
        y: 0.0,
        width: 3024.0,
        height: 1964.0,
    };
    const EXTERNAL: ScreenBounds = ScreenBounds {
        x: -197.0,
        y: -1080.0,
        width: 1920.0,
        height: 1080.0,
    };

    #[test]
    fn picks_the_display_the_tray_is_on() {
        let screens = [LAPTOP, EXTERNAL];
        assert_eq!(screen_containing(&screens, 1512.0, 100.0), Some(LAPTOP));
        assert_eq!(screen_containing(&screens, 500.0, -1070.0), Some(EXTERNAL));
    }

    #[test]
    fn sits_under_the_tray_on_a_1x_display_above_the_laptop() {
        let (x, y, placement) =
            popover_origin(500.0, -1080.0, 40.0, 24.0, 340.0, 326.0, EXTERNAL);
        assert_eq!(x, 350.0);
        assert_eq!(y, -1054.0);
        assert_eq!(placement, PopoverPlacement::Below);
        assert!(point_in_screen(x, y, EXTERNAL));
        assert!(!point_in_screen(x, y, LAPTOP));
    }

    #[test]
    fn sits_under_the_tray_on_the_built_in_display() {
        let (x, y, placement) = popover_origin(
            1200.0,
            0.0,
            40.0,
            24.0,
            340.0,
            326.0,
            ScreenBounds {
                x: 0.0,
                y: 0.0,
                width: 1512.0,
                height: 982.0,
            },
        );
        assert_eq!(x, 1050.0);
        assert_eq!(y, 26.0);
        assert_eq!(placement, PopoverPlacement::Below);
    }

    #[test]
    fn stays_on_the_tray_screen_when_the_icon_is_near_the_edge() {
        let (x, y, placement) =
            popover_origin(-180.0, -1080.0, 40.0, 24.0, 340.0, 326.0, EXTERNAL);
        assert_eq!(x, EXTERNAL.x + 8.0);
        assert_eq!(y, -1054.0);
        assert_eq!(placement, PopoverPlacement::Below);
        assert!(point_in_screen(x, y, EXTERNAL));
    }

    #[test]
    fn caret_stays_on_the_icon_when_the_window_is_centered() {
        assert_eq!(caret_offset(370.0, 300.0, 500.0, 40.0), 150.0);
    }

    #[test]
    fn caret_follows_the_icon_when_the_window_is_clamped() {
        assert_eq!(caret_offset(-189.0, 340.0, -180.0, 40.0), 29.0);
    }

    #[test]
    fn caret_stays_inside_the_card_near_a_corner() {
        assert_eq!(caret_offset(8.0, 300.0, 8.0, 24.0), 22.0);
    }
}
